services:
  - type: web
    name: n8n
    runtime: docker
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "user"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "2@25_n*N"
